spring:
  application:
    name: sample-client
  ai:
    mcp:
      client:
        sse:
          connections:
            sample-server-http:
              url: http://localhost:8081
            #github-server-http:
            #  url: http://localhost:8082
        #stdio:
        #  servers-configuration: classpath:mcp-servers.json
        toolcallback:
          enabled: true
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini

logging:
  level:
    io:
      modelcontextprotocol:
        client: WARN
        spec: WARN