name: Sample Server HTTP CI

on:
  push:
    branches: [ main ]
    paths:
      - 'sample-server-http/**'
      - '.github/workflows/sample-server-http.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'sample-server-http/**'
      - '.github/workflows/sample-server-http.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file sample-server-http/pom.xml
    
    - name: Test with Maven
      run: mvn -B test --file sample-server-http/pom.xml